language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt


after_success: |
  if [ -n "$public_token" ]; then
    cd "$TRAVIS_BUILD_DIR"
    # This generates a `web` directory containing the website.
    make web
    cd web
    git init
    python write_readme.py
    git add .
    git -c user.name='travis' -c user.email='travis' commit -m init
    # Make sure to make the output quiet, or else the API token will leak!
    # This works because the API key can replace your password.
    git push -f -q https://dapangmao:$public_token@github.com/dapangmao/go4fun
    cd "$TRAVIS_BUILD_DIR"
  fi