[['Two Sum', 'free', 'Easy', 84.08],
 ['Add Two Numbers', 'free', 'Medium', 83.15],
 ['Trapping Rain Water', 'free', 'Hard', 82.22],
 ['LRU Cache', 'free', 'Medium', 81.82],
 ['Longest Palindromic Substring', 'free', 'Medium', 81.74],
 ['Median of Two Sorted Arrays', 'free', 'Hard', 80.81],
 ['Number of Islands', 'free', 'Medium', 79.88],
 ['Longest Substring Without Repeating Characters', 'free', 'Medium', 78.95],
 ['Maximum Subarray', 'free', 'Easy', 78.31],
 ['3Sum', 'free', 'Medium', 78.1],
 ['Valid Parentheses', 'free', 'Easy', 77.65],
 ['Merge Two Sorted Lists', 'free', 'Easy', 76.72],
 ['Reorder Data in Log Files', 'free', 'Easy', 75.79],
 ['Merge k Sorted Lists', 'free', 'Hard', 75.05],
 ['Product of Array Except Self', 'free', 'Medium', 74.12],
 ['Merge Intervals', 'free', 'Medium', 73.19],
 ['Reverse Linked List', 'free', 'Easy', 72.75],
 ['Happy Number', 'free', 'Easy', 71.92],
 ['Minimum Window Substring', 'free', 'Hard', 71.82],
 ['Minimum Domino Rotations For Equal Row', 'free', 'Medium', 71.33],
 ['Game of Life', 'free', 'Medium', 70.45],
 ['Generate Parentheses', 'free', 'Medium', 69.88],
 ['Serialize and Deserialize Binary Tree', 'free', 'Hard', 69.38],
 ['Integer to English Words', 'free', 'Hard', 69.35],
 ['Remove Invalid Parentheses', 'free', 'Hard', 68.99],
 ['Search in Rotated Sorted Array', 'free', 'Medium', 68.64],
 ['Meeting Rooms II', 'locked', 'Medium', 67.71],
 ['Best Time to Buy and Sell Stock', 'free', 'Easy', 67.34],
 ['Subarray Sum Equals K', 'free', 'Medium', 66.41],
 ['Group Anagrams', 'free', 'Medium', 66.14],
 ['Container With Most Water', 'free', 'Medium', 65.59],
 ['Find Duplicate File in System', 'free', 'Medium', 65.46],
 ['Decode String', 'free', 'Medium', 65.04],
 ['Spiral Matrix', 'free', 'Medium', 64.93],
 ['Decode Ways', 'free', 'Medium', 64.91],
 ['Alien Dictionary', 'locked', 'Hard', 64.73],
 ['Text Justification', 'free', 'Hard', 64.54],
 ['First Missing Positive', 'free', 'Hard', 64.54],
 ['Merge Sorted Array', 'free', 'Easy', 64.45],
 ['Copy List with Random Pointer', 'free', 'Medium', 64.15],
 ['Palindrome Pairs', 'free', 'Hard', 64.08],
 ['K Closest Points to Origin', 'free', 'Medium', 64.07],
 ['Next Permutation', 'free', 'Medium', 63.26],
 ['Reconstruct Itinerary', 'free', 'Medium', 63.18],
 ['Reverse Integer', 'free', 'Easy', 63.11],
 ['Insert Delete GetRandom O(1)', 'free', 'Medium', 63.0],
 ['Maximal Rectangle', 'free', 'Hard', 62.07],
 ['Letter Combinations of a Phone Number', 'free', 'Medium', 61.96],
 ['Regular Expression Matching', 'free', 'Hard', 61.9],
 ['Permutations', 'free', 'Medium', 61.83],
 ['Word Search', 'free', 'Medium', 61.62],
 ['Critical Connections in a Network', 'free', 'Hard', 61.35],
 ['Word Ladder', 'free', 'Medium', 61.16],
 ['Coin Change', 'free', 'Medium', 60.46],
 ['Time Based Key-Value Store', 'free', 'Medium', 60.28],
 ['The Skyline Problem', 'free', 'Hard', 60.16],
 ['Word Break', 'free', 'Medium', 59.81],
 ['Binary Tree Maximum Path Sum', 'free', 'Hard', 58.75],
 ['Design Search Autocomplete System', 'locked', 'Hard', 58.72],
 ['Maximal Square', 'free', 'Medium', 58.61],
 ['Roman to Integer', 'free', 'Easy', 58.14],
 ['Burst Balloons', 'free', 'Hard', 57.66],
 ['Longest Valid Parentheses', 'free', 'Hard', 57.6],
 ['Edit Distance', 'free', 'Hard', 57.56],
 ['Fraction to Recurring Decimal', 'free', 'Medium', 57.35],
 ['Valid Palindrome', 'free', 'Easy', 57.16],
 ['Reverse String', 'free', 'Easy', 57.1],
 ['Fizz Buzz', 'free', 'Easy', 56.71],
 ['Friend Circles', 'free', 'Medium', 56.67],
 ['Split Array Largest Sum', 'free', 'Hard', 56.49],
 ['Min Stack', 'free', 'Easy', 56.39],
 ['Word Search II', 'free', 'Hard', 56.34],
 ['Jump Game II', 'free', 'Hard', 56.33],
 ['Asteroid Collision', 'free', 'Medium', 56.07],
 ['Basic Calculator II', 'free', 'Medium', 56.03],
 ['Swap Nodes in Pairs', 'free', 'Medium', 56.01],
 ['Interleaving String', 'free', 'Hard', 55.72],
 ['Find Median from Data Stream', 'free', 'Hard', 55.58],
 ['Flatten Nested List Iterator', 'free', 'Medium', 55.55],
 ['Climbing Stairs', 'free', 'Easy', 55.41],
 ['Integer to Roman', 'free', 'Medium', 55.28],
 ['Task Scheduler', 'free', 'Medium', 55.25],
 ['Kth Largest Element in an Array', 'free', 'Medium', 55.04],
 ['Palindrome Number', 'free', 'Easy', 55.0],
 ['Binary Tree Right Side View', 'free', 'Medium', 54.95],
 ['Design Hit Counter', 'locked', 'Medium', 54.39],
 ['ZigZag Conversion', 'free', 'Medium', 54.27],
 ['Sliding Window Maximum', 'free', 'Hard', 54.22],
 ['N-Queens', 'free', 'Hard', 54.11],
 ['Serialize and Deserialize BST', 'free', 'Medium', 53.95],
 ['Count of Smaller Numbers After Self', 'free', 'Hard', 53.84],
 ['Search a 2D Matrix II', 'free', 'Medium', 53.72],
 ['Lowest Common Ancestor of a Binary Tree', 'free', 'Medium', 53.69],
 ['Validate Binary Search Tree', 'free', 'Medium', 53.44],
 ['Move Zeroes', 'free', 'Easy', 53.36],
 ['Flatten a Multilevel Doubly Linked List', 'free', 'Medium', 52.88],
 ['Combination Sum', 'free', 'Medium', 52.88],
 ['Interval List Intersections', 'free', 'Medium', 52.88],
 ['Reverse Linked List II', 'free', 'Medium', 52.85],
 ['First Unique Character in a String', 'free', 'Easy', 52.82],
 ['Subdomain Visit Count', 'free', 'Easy', 52.69],
 ['Rotate Image', 'free', 'Medium', 52.58],
 ['Add Binary', 'free', 'Easy', 52.48],
 ['Encode and Decode TinyURL', 'free', 'Medium', 52.46],
 ['Longest Common Prefix', 'free', 'Easy', 52.22],
 ['Basic Calculator', 'free', 'Hard', 52.2],
 ['LFU Cache', 'free', 'Hard', 52.18],
 ['String to Integer (atoi)', 'free', 'Medium', 52.11],
 ['Add Two Numbers II', 'free', 'Medium', 52.08],
 ['Subsets', 'free', 'Medium', 52.04],
 ['Max Stack', 'locked', 'Easy', 51.86],
 ['Reaching Points', 'free', 'Hard', 51.86],
 ['Reverse Nodes in k-Group', 'free', 'Hard', 51.75],
 ['Employee Free Time', 'locked', 'Hard', 51.61],
 ['String Compression', 'free', 'Easy', 51.4],
 ['Cherry Pickup', 'free', 'Hard', 51.32],
 ['Word Ladder II', 'free', 'Hard', 51.06],
 ['Sudoku Solver', 'free', 'Hard', 51.03],
 ['Insert Interval', 'free', 'Hard', 50.95],
 ['Design Tic-Tac-Toe', 'locked', 'Medium', 50.61],
 ['Wildcard Matching', 'free', 'Hard', 50.55],
 ['Top K Frequent Elements', 'free', 'Medium', 50.55],
 ['Reorder List', 'free', 'Medium', 50.22],
 ['Simplify Path', 'free', 'Medium', 50.15],
 ['Multiply Strings', 'free', 'Medium', 50.11],
 ['Shortest Distance from All Buildings', 'locked', 'Hard', 50.08],
 ['4Sum', 'free', 'Medium', 50.04],
 ['Restore IP Addresses', 'free', 'Medium', 50.02],
 ['Word Break II', 'free', 'Hard', 49.98],
 ['Max Points on a Line', 'free', 'Hard', 49.96],
 ['Maximum Product Subarray', 'free', 'Medium', 49.85],
 ['3Sum Closest', 'free', 'Medium', 49.84],
 ['Convert Binary Search Tree to Sorted Doubly Linked List',
  'locked',
  'Medium',
  49.62],
 ['Top K Frequent Words', 'free', 'Medium', 49.55],
 ['Binary Tree Zigzag Level Order Traversal', 'free', 'Medium', 49.52],
 ['Max Area of Island', 'free', 'Medium', 49.29],
 ['Palindromic Substrings', 'free', 'Medium', 49.28],
 ['Longest Consecutive Sequence', 'free', 'Hard', 49.19],
 ['Longest Increasing Subsequence', 'free', 'Medium', 48.72],
 ['Sort List', 'free', 'Medium', 48.69],
 ['All Nodes Distance K in Binary Tree', 'free', 'Medium', 48.54],
 ['Construct Binary Tree from Preorder and Inorder Traversal',
  'free',
  'Medium',
  48.46],
 ['Binary Search Tree Iterator', 'free', 'Medium', 48.45],
 ['Find First and Last Position of Element in Sorted Array',
  'free',
  'Medium',
  48.4],
 ['House Robber', 'free', 'Easy', 48.18],
 ['Clone Graph', 'free', 'Medium', 48.14],
 ['Best Time to Buy and Sell Stock III', 'free', 'Hard', 48.13],
 ['Course Schedule', 'free', 'Medium', 47.97],
 ['Evaluate Reverse Polish Notation', 'free', 'Medium', 47.95],
 ['Design HashMap', 'free', 'Easy', 47.94],
 ['Random Pick with Weight', 'free', 'Medium', 47.93],
 ['Basic Calculator III', 'locked', 'Hard', 47.92],
 ['Find All Anagrams in a String', 'free', 'Medium', 47.81],
 ['Valid Anagram', 'free', 'Easy', 47.78],
 ['Diagonal Traverse', 'free', 'Medium', 47.77],
 ['Add Strings', 'free', 'Easy', 47.7],
 ['Minimum Path Sum', 'free', 'Medium', 47.65],
 ['All O`one Data Structure', 'free', 'Hard', 47.53],
 ['Daily Temperatures', 'free', 'Medium', 47.38],
 ['Summary Ranges', 'free', 'Medium', 47.37],
 ['Frog Jump', 'free', 'Hard', 47.37],
 ['Guess the Word', 'free', 'Hard', 47.36],
 ['Sort Colors', 'free', 'Medium', 47.12],
 ['Pow(x, n)', 'free', 'Medium', 47.12],
 ['Contiguous Array', 'free', 'Medium', 47.09],
 ['Minimum Size Subarray Sum', 'free', 'Medium', 46.93],
 ['Reverse Words in a String', 'free', 'Medium', 46.82],
 ['Campus Bikes', 'locked', 'Medium', 46.45],
 ['Diameter of Binary Tree', 'free', 'Easy', 46.28],
 ['Design Log Storage System', 'locked', 'Medium', 46.21],
 ['Vertical Order Traversal of a Binary Tree', 'free', 'Medium', 46.19],
 ['Shortest Word Distance II', 'locked', 'Medium', 46.14],
 ['Binary Tree Level Order Traversal', 'free', 'Medium', 46.08],
 ['Longest Substring with At Most K Distinct Characters',
  'locked',
  'Hard',
  45.87],
 ['Course Schedule II', 'free', 'Medium', 45.86],
 ['Convert Sorted List to Binary Search Tree', 'free', 'Medium', 45.75],
 ['Valid Sudoku', 'free', 'Medium', 45.52],
 ['Find the Celebrity', 'locked', 'Medium', 45.44],
 ['Count Complete Tree Nodes', 'free', 'Medium', 45.44],
 ['Subarray Sums Divisible by K', 'free', 'Medium', 45.39],
 ['Accounts Merge', 'free', 'Medium', 45.37],
 ['Palindrome Linked List', 'free', 'Easy', 45.33],
 ['Divide Two Integers', 'free', 'Medium', 45.31],
 ['Remove All Adjacent Duplicates In String', 'free', 'Easy', 45.28],
 ['Design Twitter', 'free', 'Medium', 45.28],
 ['Rectangle Overlap', 'free', 'Easy', 45.27],
 ['Jewels and Stones', 'free', 'Easy', 45.05],
 ['Longest Increasing Path in a Matrix', 'free', 'Hard', 44.78],
 ['Flood Fill', 'free', 'Easy', 44.67],
 ['Implement Trie (Prefix Tree)', 'free', 'Medium', 44.66],
 ['Count Primes', 'free', 'Easy', 44.64],
 ['Odd Even Linked List', 'free', 'Medium', 44.59],
 ['Two Sum II - Input array is sorted', 'free', 'Easy', 44.55],
 ['Intersection of Two Arrays II', 'free', 'Easy', 44.3],
 ['Coin Change 2', 'free', 'Medium', 44.27],
 ['Gas Station', 'free', 'Medium', 44.11],
 ['Shortest Palindrome', 'free', 'Hard', 44.06],
 ['Remove Linked List Elements', 'free', 'Easy', 44.03],
 ['Minesweeper', 'free', 'Medium', 43.95],
 ['Intersection of Two Arrays', 'free', 'Easy', 43.85],
 ['Find All Duplicates in an Array', 'free', 'Medium', 43.82],
 ['Partition to K Equal Sum Subsets', 'free', 'Medium', 43.78],
 ['Moving Average from Data Stream', 'locked', 'Easy', 43.77],
 ['Queue Reconstruction by Height', 'free', 'Medium', 43.59],
 ['Cheapest Flights Within K Stops', 'free', 'Medium', 43.53],
 ['Best Time to Buy and Sell Stock with Cooldown', 'free', 'Medium', 43.22],
 ['Sqrt(x)', 'free', 'Easy', 43.19],
 ['Largest Rectangle in Histogram', 'free', 'Hard', 43.18],
 ['Concatenated Words', 'free', 'Hard', 43.04],
 ['Linked List Cycle', 'free', 'Easy', 42.96],
 ['Remove Nth Node From End of List', 'free', 'Medium', 42.82],
 ['Unique Binary Search Trees', 'free', 'Medium', 42.76],
 ['Reorganize String', 'free', 'Medium', 42.58],
 ['Subtree of Another Tree', 'free', 'Easy', 42.57],
 ['Single Number II', 'free', 'Medium', 42.53],
 ['Find Peak Element', 'free', 'Medium', 42.5],
 ['Exclusive Time of Functions', 'free', 'Medium', 42.42],
 ['Word Frequency', 'free', 'Medium', 42.39],
 ['Print in Order', 'free', 'Easy', 42.39],
 ['Recover Binary Search Tree', 'free', 'Hard', 42.32],
 ['Fibonacci Number', 'free', 'Easy', 42.31],
 ['Serialize and Deserialize N-ary Tree', 'locked', 'Hard', 42.3],
 ['Find the Closest Palindrome', 'free', 'Hard', 42.26],
 ['Single Number', 'free', 'Easy', 42.14],
 ['Find Minimum in Rotated Sorted Array', 'free', 'Medium', 42.09],
 ['Symmetric Tree', 'free', 'Easy', 41.72],
 ['Substring with Concatenation of All Words', 'free', 'Hard', 41.71],
 ['Spiral Matrix II', 'free', 'Medium', 41.21],
 ['Missing Number', 'free', 'Easy', 41.1],
 ['Largest Number', 'free', 'Medium', 41.07],
 ['Pacific Atlantic Water Flow', 'free', 'Medium', 40.78],
 ['Palindrome Partitioning', 'free', 'Medium', 40.77],
 ['Count and Say', 'free', 'Easy', 40.7],
 ['Populating Next Right Pointers in Each Node', 'free', 'Medium', 40.61],
 ['Longest Absolute File Path', 'free', 'Medium', 40.6],
 ['Range Sum Query 2D - Immutable', 'free', 'Medium', 40.55],
 ['Implement strStr()', 'free', 'Easy', 40.53],
 ['Remove Duplicate Letters', 'free', 'Hard', 40.41],
 ['Best Time to Buy and Sell Stock IV', 'free', 'Hard', 40.4],
 ['Prison Cells After N Days', 'free', 'Medium', 40.38],
 ['Wiggle Sort', 'locked', 'Medium', 40.35],
 ['Find the Duplicate Number', 'free', 'Medium', 40.17],
 ['Pascal&#39;s Triangle', 'free', 'Easy', 40.11],
 ['Unique Paths', 'free', 'Medium', 40.07],
 ['Add and Search Word - Data structure design', 'free', 'Medium', 39.79],
 ['Boundary of Binary Tree', 'locked', 'Medium', 39.63],
 ['Most Common Word', 'free', 'Easy', 39.58],
 ['Majority Element', 'free', 'Easy', 39.42],
 ['Flatten Binary Tree to Linked List', 'free', 'Medium', 39.32],
 ['Is Graph Bipartite?', 'free', 'Medium', 39.28],
 ['Shortest Path in Binary Matrix', 'free', 'Medium', 39.0],
 ['Remove Duplicates from Sorted Array', 'free', 'Easy', 38.92],
 ['Intersection of Two Linked Lists', 'free', 'Easy', 38.9],
 ['Surrounded Regions', 'free', 'Medium', 38.61],
 ['Squares of a Sorted Array', 'free', 'Easy', 38.42],
 ['Partition Equal Subset Sum', 'free', 'Medium', 38.41],
 ['Sliding Puzzle', 'free', 'Hard', 38.35],
 ['Find Leaves of Binary Tree', 'locked', 'Medium', 38.35],
 ['Next Greater Element III', 'free', 'Medium', 38.27],
 ['Design Snake Game', 'locked', 'Medium', 38.26],
 ['Kth Smallest Element in a Sorted Matrix', 'free', 'Medium', 38.24],
 ['Robot Room Cleaner', 'locked', 'Hard', 38.21],
 ['Increasing Triplet Subsequence', 'free', 'Medium', 38.1],
 ['Rotate Array', 'free', 'Easy', 38.08],
 ['Best Time to Buy and Sell Stock II', 'free', 'Easy', 38.06],
 ['All Paths From Source to Target', 'free', 'Medium', 37.88],
 ['Closest Leaf in a Binary Tree', 'locked', 'Medium', 37.73],
 ['Sliding Window Median', 'free', 'Hard', 37.72],
 ['Binary Tree Inorder Traversal', 'free', 'Medium', 37.68],
 ['Largest BST Subtree', 'locked', 'Medium', 37.65],
 ['Majority Element II', 'free', 'Medium', 37.6],
 ['132 Pattern', 'free', 'Medium', 37.54],
 ['Maximum Depth of Binary Tree', 'free', 'Easy', 37.43],
 ['License Key Formatting', 'free', 'Easy', 37.42],
 ['Unique Paths III', 'free', 'Hard', 37.17],
 ['Binary Tree Vertical Order Traversal', 'locked', 'Medium', 37.16],
 ['Permutation in String', 'free', 'Medium', 36.83],
 ['Remove Duplicates from Sorted List II', 'free', 'Medium', 36.75],
 ['Different Ways to Add Parentheses', 'free', 'Medium', 36.62],
 ['Knight Probability in Chessboard', 'free', 'Medium', 36.55],
 ['Partition Labels', 'free', 'Medium', 36.51],
 ['Pairs of Songs With Total Durations Divisible by 60', 'free', 'Easy', 36.43],
 ['Isomorphic Strings', 'free', 'Easy', 36.37],
 ['Video Stitching', 'free', 'Medium', 36.27],
 ['Jump Game', 'free', 'Medium', 36.18],
 ['Permutations II', 'free', 'Medium', 36.16],
 ['Design In-Memory File System', 'locked', 'Hard', 36.12],
 ['One Edit Distance', 'locked', 'Medium', 36.12],
 ['Logger Rate Limiter', 'locked', 'Easy', 36.08],
 ['Search in Rotated Sorted Array II', 'free', 'Medium', 35.98],
 ['Insert Delete GetRandom O(1) - Duplicates allowed', 'free', 'Hard', 35.89],
 ['Insert into a Cyclic Sorted List', 'locked', 'Medium', 35.53],
 ['Combination Sum II', 'free', 'Medium', 35.53],
 ['Partition List', 'free', 'Medium', 35.33],
 ['Longest Palindromic Subsequence', 'free', 'Medium', 35.33],
 ['Shortest Word Distance', 'locked', 'Easy', 35.3],
 ['Snakes and Ladders', 'free', 'Medium', 35.26],
 ['Nested List Weight Sum', 'locked', 'Easy', 35.25],
 ['Closest Binary Search Tree Value II', 'locked', 'Hard', 35.23],
 ['Convert BST to Greater Tree', 'free', 'Easy', 35.19],
 ['Campus Bikes II', 'locked', 'Medium', 35.17],
 ['Convert Sorted Array to Binary Search Tree', 'free', 'Easy', 34.84],
 ['Design Circular Queue', 'free', 'Medium', 34.83],
 ['Range Sum of BST', 'free', 'Easy', 34.78],
 ['Custom Sort String', 'free', 'Medium', 34.72],
 ['Validate IP Address', 'free', 'Medium', 34.69],
 ['Candy', 'free', 'Hard', 34.58],
 ['Lowest Common Ancestor of a Binary Search Tree', 'free', 'Easy', 34.54],
 ['Number of Atoms', 'free', 'Hard', 34.37],
 ['Rotting Oranges', 'free', 'Easy', 34.36],
 ['Invert Binary Tree', 'free', 'Easy', 34.35],
 ['High Five', 'locked', 'Easy', 34.34],
 ['Flatten 2D Vector', 'locked', 'Medium', 34.18],
 ['Count Univalue Subtrees', 'locked', 'Medium', 34.15],
 ['Longest Substring with At Least K Repeating Characters',
  'free',
  'Medium',
  34.15],
 ['Stream of Characters', 'free', 'Hard', 34.09],
 ['Trapping Rain Water II', 'free', 'Hard', 34.0],
 ['Walls and Gates', 'locked', 'Medium', 33.96],
 ['Path Sum II', 'free', 'Medium', 33.85],
 ['Valid Triangle Number', 'free', 'Medium', 33.81],
 ['Compare Version Numbers', 'free', 'Medium', 33.77],
 ['Bus Routes', 'free', 'Hard', 33.72],
 ['Remove Duplicates from Sorted List', 'free', 'Easy', 33.68],
 ['Longest Common Subsequence', 'free', 'Medium', 33.66],
 ['Perfect Squares', 'free', 'Medium', 33.6],
 ['Last Stone Weight', 'free', 'Easy', 33.59],
 ['Find the Shortest Superstring', 'free', 'Hard', 33.57],
 ['Single Element in a Sorted Array', 'free', 'Medium', 33.56],
 ['Relative Sort Array', 'free', 'Easy', 33.53],
 ['Elimination Game', 'free', 'Medium', 33.46],
 ['Basic Calculator IV', 'free', 'Hard', 33.42],
 ['Prime Palindrome', 'free', 'Medium', 33.36],
 ['Path Sum III', 'free', 'Easy', 33.29],
 ['Create Maximum Number', 'free', 'Hard', 33.21],
 ['Binary Tree Paths', 'free', 'Easy', 33.13],
 ['Set Matrix Zeroes', 'free', 'Medium', 32.89],
 ['Number of Digit One', 'free', 'Hard', 32.81],
 ['Evaluate Division', 'free', 'Medium', 32.76],
 ['Missing Ranges', 'locked', 'Medium', 32.74],
 ['Search a 2D Matrix', 'free', 'Medium', 32.58],
 ['Ugly Number II', 'free', 'Medium', 32.55],
 ['Implement Queue using Stacks', 'free', 'Easy', 32.43],
 ['Kth Largest Element in a Stream', 'free', 'Easy', 32.42],
 ['Implement Stack using Queues', 'free', 'Easy', 32.39],
 ['Rotate List', 'free', 'Medium', 32.34],
 ['Smallest Range Covering Elements from K Lists', 'free', 'Hard', 32.14],
 ['Shuffle an Array', 'free', 'Medium', 32.1],
 ['The Maze', 'locked', 'Medium', 31.97],
 ['Plus One', 'free', 'Easy', 31.76],
 ['Path Sum', 'free', 'Easy', 31.58],
 ['Find K Pairs with Smallest Sums', 'free', 'Medium', 31.55],
 ['Populating Next Right Pointers in Each Node II', 'free', 'Medium', 31.5],
 ['Minimum Cost For Tickets', 'free', 'Medium', 31.49],
 ['Third Maximum Number', 'free', 'Easy', 31.4],
 ['Kth Smallest Element in a BST', 'free', 'Medium', 31.32],
 ['Number of Distinct Islands', 'locked', 'Medium', 31.28],
 ['Minimum Area Rectangle', 'free', 'Medium', 31.01],
 ['Inorder Successor in BST', 'locked', 'Medium', 30.99],
 ['Excel Sheet Column Number', 'free', 'Easy', 30.95],
 ['Next Greater Element I', 'free', 'Easy', 30.93],
 ['Max Increase to Keep City Skyline', 'free', 'Medium', 30.77],
 ['Longest Duplicate Substring', 'free', 'Hard', 30.76],
 ['Triangle', 'free', 'Medium', 30.62],
 ['Minimum Cost to Merge Stones', 'free', 'Hard', 30.16],
 ['Remove K Digits', 'free', 'Medium', 30.15],
 ['Construct Binary Search Tree from Preorder Traversal',
  'free',
  'Medium',
  30.02],
 ['Split Array With Same Average', 'free', 'Hard', 29.9],
 ['Island Perimeter', 'free', 'Easy', 29.81],
 ['Maximum Frequency Stack', 'free', 'Hard', 29.73],
 ['Bulls and Cows', 'free', 'Easy', 29.71],
 ['Meeting Rooms', 'locked', 'Easy', 29.6],
 ['Graph Valid Tree', 'locked', 'Medium', 29.59],
 ['Bomb Enemy', 'locked', 'Medium', 29.41],
 ['Next Greater Element II', 'free', 'Medium', 29.35],
 ['Palindrome Partitioning II', 'free', 'Hard', 29.27],
 ['Construct Binary Tree from Inorder and Postorder Traversal',
  'free',
  'Medium',
  29.25],
 ['Min Cost Climbing Stairs', 'free', 'Easy', 29.22],
 ['Maximum Product of Three Numbers', 'free', 'Easy', 29.1],
 ['Minimum Window Subsequence', 'locked', 'Hard', 29.09],
 ['Max Consecutive Ones III', 'free', 'Medium', 29.02],
 ['Remove Comments', 'free', 'Medium', 28.71],
 ['Find Duplicate Subtrees', 'free', 'Medium', 28.61],
 ['01 Matrix', 'free', 'Medium', 28.59],
 ['Merge Two Binary Trees', 'free', 'Easy', 28.54],
 ['Unique Paths II', 'free', 'Medium', 28.21],
 ['Same Tree', 'free', 'Easy', 28.05],
 ['Balanced Binary Tree', 'free', 'Easy', 28.04],
 ['Delete Node in a Linked List', 'free', 'Easy', 27.92],
 ['Longest Turbulent Subarray', 'free', 'Medium', 27.91],
 ['Number of Connected Components in an Undirected Graph',
  'locked',
  'Medium',
  27.83],
 ['My Calendar I', 'free', 'Medium', 27.79],
 ['Delete Node in a BST', 'free', 'Medium', 27.75],
 ['Distinct Subsequences', 'free', 'Hard', 27.73],
 ['Number of Dice Rolls With Target Sum', 'free', 'Medium', 27.59],
 ['Design Excel Sum Formula', 'locked', 'Hard', 27.45],
 ['K-diff Pairs in an Array', 'free', 'Easy', 27.41],
 ['Linked List Cycle II', 'free', 'Medium', 27.38],
 ['Shortest Unsorted Continuous Subarray', 'free', 'Easy', 27.3],
 ['Data Stream as Disjoint Intervals', 'free', 'Hard', 27.25],
 ['Minimum Cost to Connect Sticks', 'locked', 'Medium', 27.13],
 ['Maximum Difference Between Node and Ancestor', 'free', 'Medium', 27.07],
 ['Find K Closest Elements', 'free', 'Medium', 27.03],
 ['Binary Search Tree to Greater Sum Tree', 'free', 'Medium', 26.81],
 ['Insert into a Binary Search Tree', 'free', 'Medium', 26.73],
 ['K-Similar Strings', 'free', 'Hard', 26.69],
 ['Reverse Vowels of a String', 'free', 'Easy', 26.37],
 ['Fruit Into Baskets', 'free', 'Medium', 26.01],
 ['Missing Element in Sorted Array', 'locked', 'Medium', 25.71],
 ['Find the Town Judge', 'free', 'Easy', 25.61],
 ['Peeking Iterator', 'free', 'Medium', 25.58],
 ['Single Number III', 'free', 'Medium', 25.53],
 ['Cut Off Trees for Golf Event', 'free', 'Hard', 25.51],
 ['Palindrome Permutation II', 'locked', 'Medium', 25.49],
 ['Sort Array By Parity', 'free', 'Easy', 25.48],
 ['Recover a Tree From Preorder Traversal', 'free', 'Hard', 25.46],
 ['Valid Tic-Tac-Toe State', 'free', 'Medium', 25.44],
 ['Two Sum Less Than K', 'locked', 'Easy', 25.13],
 ['Palindrome Permutation', 'locked', 'Easy', 25.03],
 ['Transpose Matrix', 'free', 'Easy', 25.02],
 ['Network Delay Time', 'free', 'Medium', 24.97],
 ['Plus One Linked List', 'locked', 'Medium', 24.85],
 ['Rearrange String k Distance Apart', 'locked', 'Hard', 24.85],
 ['Longest Repeating Substring', 'locked', 'Medium', 24.84],
 ['Number of Submatrices That Sum to Target', 'free', 'Hard', 24.47],
 ['Subarrays with K Different Integers', 'free', 'Hard', 24.43],
 ['Robot Return to Origin', 'free', 'Easy', 24.41],
 ['Minimum Swaps To Make Sequences Increasing', 'free', 'Medium', 24.4],
 ['Counting Bits', 'free', 'Medium', 24.38],
 ['Closest Binary Search Tree Value', 'locked', 'Easy', 24.36],
 ['Longest Palindrome', 'free', 'Easy', 24.29],
 ['Height Checker', 'free', 'Easy', 24.25],
 ['Range Sum Query - Mutable', 'free', 'Medium', 24.24],
 ['Unique Email Addresses', 'free', 'Easy', 24.19],
 ['Subsets II', 'free', 'Medium', 24.12],
 ['Maximum Size Subarray Sum Equals k', 'locked', 'Medium', 24.06],
 ['Path In Zigzag Labelled Binary Tree', 'free', 'Medium', 23.94],
 ['Contains Duplicate', 'free', 'Easy', 23.83],
 ['RLE Iterator', 'free', 'Medium', 23.76],
 ['Binary Tree Postorder Traversal', 'free', 'Hard', 23.76],
 ['Repeated DNA Sequences', 'free', 'Medium', 23.73],
 ['Peak Index in a Mountain Array', 'free', 'Easy', 23.61],
 ['Power of Two', 'free', 'Easy', 23.55],
 ['Two City Scheduling', 'free', 'Easy', 23.51],
 ['Sentence Similarity II', 'locked', 'Medium', 23.49],
 ['Maximum Gap', 'free', 'Hard', 23.49],
 ['Zigzag Iterator', 'locked', 'Medium', 23.43],
 ['Car Pooling', 'free', 'Medium', 23.35],
 ['Minimum Number of Arrows to Burst Balloons', 'free', 'Medium', 23.17],
 ['Word Pattern', 'free', 'Easy', 22.98],
 ['Keys and Rooms', 'free', 'Medium', 22.83],
 ['Rotate String', 'free', 'Easy', 22.44],
 ['Two Sum IV - Input is a BST', 'free', 'Easy', 22.42],
 ['Split BST', 'locked', 'Medium', 22.34],
 ['Line Reflection', 'locked', 'Medium', 22.18],
 ['Next Greater Node In Linked List', 'free', 'Medium', 22.17],
 ['Sort Characters By Frequency', 'free', 'Medium', 22.16],
 ['N-ary Tree Level Order Traversal', 'free', 'Medium', 21.98],
 ['Distribute Coins in Binary Tree', 'free', 'Medium', 21.98],
 ['Maximum Length of Pair Chain', 'free', 'Medium', 21.96],
 ['4Sum II', 'free', 'Medium', 21.8],
 ['Binary Tree Preorder Traversal', 'free', 'Medium', 21.54],
 ['Reverse String II', 'free', 'Easy', 20.66],
 ['DI String Match', 'free', 'Easy', 20.62],
 ['Pascal&#39;s Triangle II', 'free', 'Easy', 20.6],
 ['Maximum Width of Binary Tree', 'free', 'Medium', 20.57],
 ['Longest Substring with At Most Two Distinct Characters',
  'locked',
  'Hard',
  20.34],
 ['Arithmetic Slices', 'free', 'Medium', 20.11],
 ['Binary Tree Longest Consecutive Sequence', 'locked', 'Medium', 20.01],
 ['Permutation Sequence', 'free', 'Medium', 20.01],
 ['Construct Binary Tree from Preorder and Postorder Traversal',
  'free',
  'Medium',
  19.97],
 ['Vowel Spellchecker', 'free', 'Medium', 19.87],
 ['Shortest Path Visiting All Nodes', 'free', 'Hard', 19.58],
 ['N-Queens II', 'free', 'Hard', 19.58],
 ['Array Partition I', 'free', 'Easy', 19.17],
 ['Search Insert Position', 'free', 'Easy', 19.04],
 ['Maximum Binary Tree', 'free', 'Medium', 18.9],
 ['The Maze II', 'locked', 'Medium', 18.69],
 ['Add Digits', 'free', 'Easy', 18.62],
 ['Sum of Left Leaves', 'free', 'Easy', 18.62],
 ['Trim a Binary Search Tree', 'free', 'Easy', 18.28],
 ['Find and Replace Pattern', 'free', 'Medium', 18.26],
 ['Gray Code', 'free', 'Medium', 18.17],
 ['Find Minimum in Rotated Sorted Array II', 'free', 'Hard', 17.51],
 ['House Robber III', 'free', 'Medium', 17.5],
 ['Search in a Sorted Array of Unknown Size', 'locked', 'Medium', 17.45],
 ['Integer Replacement', 'free', 'Medium', 17.23],
 ['Flip Equivalent Binary Trees', 'free', 'Medium', 17.21],
 ['Remove Element', 'free', 'Easy', 17.14],
 ['Maximum Depth of N-ary Tree', 'free', 'Easy', 17.08],
 ['Non-overlapping Intervals', 'free', 'Medium', 17.07],
 ['Analyze User Website Visit Pattern', 'locked', 'Medium', 16.88],
 ['Reverse Words in a String II', 'locked', 'Medium', 16.88],
 ['Lemonade Change', 'free', 'Easy', 16.7],
 ['Average of Levels in Binary Tree', 'free', 'Easy', 16.6],
 ['Minimum Depth of Binary Tree', 'free', 'Easy', 16.59],
 ['Minimum Number of Refueling Stops', 'free', 'Hard', 16.34],
 ['Complete Binary Tree Inserter', 'free', 'Medium', 16.32],
 ['Split Linked List in Parts', 'free', 'Medium', 16.29],
 ['Valid Parenthesis String', 'free', 'Medium', 16.01],
 ['Perfect Number', 'free', 'Easy', 15.97],
 ['My Calendar II', 'free', 'Medium', 15.71],
 ['Random Pick with Blacklist', 'free', 'Hard', 15.19],
 ['Kill Process', 'locked', 'Medium', 15.16],
 ['Number of Islands II', 'locked', 'Hard', 14.87],
 ['Binary Tree Longest Consecutive Sequence II', 'locked', 'Medium', 14.86],
 ['Number of 1 Bits', 'free', 'Easy', 14.73],
 ['Connecting Cities With Minimum Cost', 'locked', 'Medium', 14.71],
 ['Most Frequent Subtree Sum', 'free', 'Medium', 14.28],
 ['Camelcase Matching', 'free', 'Medium', 14.25],
 ['Find K-th Smallest Pair Distance', 'free', 'Hard', 14.16],
 ['Dungeon Game', 'free', 'Hard', 14.01],
 ['Number of Equivalent Domino Pairs', 'free', 'Easy', 13.96],
 ['Maximum Average Subtree', 'locked', 'Medium', 13.84],
 ['Most Profit Assigning Work', 'free', 'Medium', 13.64],
 ['Cousins in Binary Tree', 'free', 'Easy', 12.75],
 ['Making A Large Island', 'free', 'Hard', 12.29],
 ['Wiggle Subsequence', 'free', 'Medium', 12.28],
 ['Longest Univalue Path', 'free', 'Easy', 12.27],
 ['Repeated Substring Pattern', 'free', 'Easy', 12.22],
 ['Sum Root to Leaf Numbers', 'free', 'Medium', 11.32],
 ['Sum of Root To Leaf Binary Numbers', 'free', 'Easy', 11.24],
 ['Sort Array By Parity II', 'free', 'Easy', 10.99],
 ['Image Smoother', 'free', 'Easy', 10.99],
 ['Remove Vowels from a String', 'locked', 'Easy', 10.93],
 ['Longest Word in Dictionary', 'free', 'Easy', 10.61],
 ['Path With Maximum Minimum Value', 'locked', 'Medium', 10.06],
 ['Reverse Bits', 'free', 'Easy', 9.9],
 ['Max Consecutive Ones', 'free', 'Easy', 9.46],
 ['My Calendar III', 'free', 'Hard', 9.27],
 ['Redundant Connection', 'free', 'Medium', 9.23],
 ['Find Words That Can Be Formed by Characters', 'free', 'Easy', 8.3],
 ['Find the Derangement of An Array', 'locked', 'Medium', 7.57],
 ['Employee Importance', 'free', 'Easy', 6.91],
 ['Find K-Length Substrings With No Repeated Characters',
  'locked',
  'Medium',
  6.21],
 ['Maximum Level Sum of a Binary Tree', 'free', 'Medium', 5.57],
 ['Global and Local Inversions', 'free', 'Medium', 5.55],
 ['Combination Sum IV', 'free', 'Medium', 5.26],
 ['Two Sum BSTs', 'locked', 'Medium', 5.17],
 ['Construct String from Binary Tree', 'free', 'Easy', 4.89],
 ['Diet Plan Performance', 'locked', 'Easy', 4.7],
 ['K Empty Slots', 'locked', 'Hard', 4.42],
 ['Minimum Distance Between BST Nodes', 'free', 'Easy', 3.49],
 ['Set Mismatch', 'free', 'Easy', 1.9],
 ['Loud and Rich', 'free', 'Medium', 0.0],
 ['Split Array into Fibonacci Sequence', 'free', 'Medium', 0.0],
 ['Numbers At Most N Given Digit Set', 'free', 'Hard', 0.0],
 ['Orderly Queue', 'free', 'Hard', 0.0],
 ['Optimal Division', 'free', 'Medium', 0.0],
 ['Complex Number Multiplication', 'free', 'Medium', 0.0],
 ['Construct Binary Tree from String', 'locked', 'Medium', 0.0],
 ['Preimage Size of Factorial Zeroes Function', 'free', 'Hard', 0.0],
 ['Number of Days in a Month', 'locked', 'Easy', 0.0],
 ['Shortest Path with Alternating Colors', 'free', 'Medium', 0.0],
 ['Super Washing Machines', 'free', 'Hard', 0.0],
 ['Largest Unique Number', 'locked', 'Easy', 0.0],
 ['Armstrong Number', 'locked', 'Easy', 0.0],
 ['Prime Number of Set Bits in Binary Representation', 'free', 'Easy', 0.0],
 ['Insufficient Nodes in Root to Leaf Paths', 'free', 'Medium', 0.0],
 ['Distant Barcodes', 'free', 'Medium', 0.0],
 ['Prime Arrangements', 'free', 'Easy', 0.0],
 ['Monotone Increasing Digits', 'free', 'Medium', 0.0],
 ['Uncrossed Lines', 'free', 'Medium', 0.0],
 ['Minimum Genetic Mutation', 'free', 'Medium', 0.0],
 ['Sum of Digits in the Minimum Number', 'locked', 'Easy', 0.0],
 ['Number of Distinct Islands II', 'locked', 'Hard', 0.0],
 ['Index Pairs of a String', 'locked', 'Easy', 0.0],
 ['Digit Count in Range', 'locked', 'Hard', 0.0],
 ['Baseball Game', 'free', 'Easy', 0.0],
 ['Rotate Function', 'free', 'Medium', 0.0],
 ['Maximum Score Words Formed by Letters', 'free', 'Hard', 0.0],
 ['Equal Tree Partition', 'locked', 'Medium', 0.0],
 ['Solve the Equation', 'free', 'Medium', 0.0]]
